require("config") -- before lazy to set local leader
require("lazy-nvim")
require("mappings")
require("colors")
require("autocommands")
require("props")
require("lualine").setup({})
require("oil").setup({})
vim.lsp.enable("lua_ls")
vim.lsp.enable("marksman")
vim.lsp.enable("zls")
vim.lsp.enable("shellcheck")
vim.lsp.enable("yamlls")
vim.lsp.enable("ts_ls")
vim.lsp.enable("terraformls")
