require("config") -- before lazy to set local leader
require("lazy-nvim")
require("mappings")
require("colors")
require("autocommands")
require("props")
require("lualine").setup({})
require("oil").setup({})
require("nvim-tree").setup({})

vim.lsp.enable("awk_ls")
vim.lsp.enable("basedpyright")
vim.lsp.enable("gopls")
vim.lsp.enable("lua_ls")
vim.lsp.enable("marksman")
vim.lsp.enable("terraformls")
vim.lsp.enable("ts_ls")
vim.lsp.enable("yamlls")
vim.lsp.enable("zls")
vim.lsp.enable("clangd")
vim.lsp.enable("helm_ls")
